-- =============================================================================
-- PlacementOS V1 Initial Schema
-- All timestamps are stored in UTC (TIMESTAMP WITH TIME ZONE).
-- Managed by Flyway. DO NOT edit this file after it has been applied.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- students
-- Stores VIT student profiles used for placement personalisation.
-- registration_number and neopat_id are the two primary lookup keys.
-- neopat_id is nullable because not every student has one at registration time.
-- -----------------------------------------------------------------------------
CREATE TABLE students (
    id                  BIGSERIAL       PRIMARY KEY,
    registration_number VARCHAR(20)     NOT NULL,
    neopat_id           VARCHAR(20),
    name                VARCHAR(255)    NOT NULL,
    branch              VARCHAR(100)    NOT NULL,
    batch               INTEGER         NOT NULL,
    cgpa                NUMERIC(4, 2)   NOT NULL CHECK (cgpa >= 0.00 AND cgpa <= 10.00),
    phone_number        VARCHAR(20),
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_students_registration_number UNIQUE (registration_number),
    CONSTRAINT uq_students_neopat_id           UNIQUE (neopat_id)
);

CREATE INDEX idx_students_registration_number ON students (registration_number);
CREATE INDEX idx_students_neopat_id           ON students (neopat_id);
CREATE INDEX idx_students_name                ON students (name);

-- -----------------------------------------------------------------------------
-- placement_drives
-- Represents a unique placement opportunity from a CDC communication.
-- eligibility_criteria is JSONB so criteria can evolve without schema changes.
-- source_email_id ties a drive back to the originating processed email.
-- status tracks the lifecycle of the drive itself.
-- -----------------------------------------------------------------------------
CREATE TABLE placement_drives (
    id                   BIGSERIAL       PRIMARY KEY,
    company_name         VARCHAR(255)    NOT NULL,
    title                VARCHAR(500),
    description          TEXT,
    received_at          TIMESTAMPTZ,
    application_deadline TIMESTAMPTZ,
    source_email_id      VARCHAR(255),
    eligibility_criteria JSONB,
    status               VARCHAR(50)     NOT NULL DEFAULT 'OPEN'
                             CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED', 'COMPLETED')),
    created_at           TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_placement_drives_company_name         ON placement_drives (company_name);
CREATE INDEX idx_placement_drives_application_deadline ON placement_drives (application_deadline);
CREATE INDEX idx_placement_drives_status               ON placement_drives (status);

-- -----------------------------------------------------------------------------
-- processed_emails
-- Idempotency guard for Gmail ingestion.
-- message_id is the external Gmail Message-ID (globally unique per message).
-- Any duplicate message_id is rejected before processing begins.
-- -----------------------------------------------------------------------------
CREATE TABLE processed_emails (
    id                BIGSERIAL       PRIMARY KEY,
    message_id        VARCHAR(255)    NOT NULL,
    thread_id         VARCHAR(255),
    source_identifier VARCHAR(255),
    received_at       TIMESTAMPTZ,
    processed_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    processing_status VARCHAR(50)     NOT NULL DEFAULT 'PENDING'
                          CHECK (processing_status IN ('PENDING', 'PROCESSED', 'FAILED', 'DUPLICATE')),
    error_message     TEXT,

    CONSTRAINT uq_processed_emails_message_id UNIQUE (message_id)
);

CREATE INDEX idx_processed_emails_message_id ON processed_emails (message_id);

-- -----------------------------------------------------------------------------
-- attachments
-- Tracks files from placement emails.
-- Files are NOT stored in the database; storage_reference points to an object
-- store or file path resolved by the processing service.
-- -----------------------------------------------------------------------------
CREATE TABLE attachments (
    id                  BIGSERIAL       PRIMARY KEY,
    placement_drive_id  BIGINT          NOT NULL REFERENCES placement_drives (id),
    filename            VARCHAR(500)    NOT NULL,
    content_type        VARCHAR(100),
    storage_reference   TEXT,
    parsed_status       VARCHAR(50)     NOT NULL DEFAULT 'PENDING'
                            CHECK (parsed_status IN ('PENDING', 'PARSED', 'FAILED', 'SKIPPED')),
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_attachments_placement_drive_id ON attachments (placement_drive_id);

-- -----------------------------------------------------------------------------
-- shortlist_entries
-- Represents a candidate found in a shortlist document.
-- At least one of registration_number, neopat_id, or candidate_name must
-- be present (enforced at application layer; schema allows flexibility).
-- source_attachment_id links back to the parsed file.
-- -----------------------------------------------------------------------------
CREATE TABLE shortlist_entries (
    id                  BIGSERIAL       PRIMARY KEY,
    placement_drive_id  BIGINT          NOT NULL REFERENCES placement_drives (id),
    registration_number VARCHAR(20),
    neopat_id           VARCHAR(20),
    candidate_name      VARCHAR(255),
    source_attachment_id BIGINT         REFERENCES attachments (id),
    match_method        VARCHAR(50),
    confidence          NUMERIC(5, 4),
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_shortlist_entries_placement_drive_id  ON shortlist_entries (placement_drive_id);
CREATE INDEX idx_shortlist_entries_registration_number ON shortlist_entries (registration_number);
CREATE INDEX idx_shortlist_entries_neopat_id           ON shortlist_entries (neopat_id);
CREATE INDEX idx_shortlist_entries_candidate_name      ON shortlist_entries (candidate_name);

-- -----------------------------------------------------------------------------
-- applications
-- Tracks an individual student's state for a placement drive.
-- The UNIQUE constraint on (student_id, placement_drive_id) prevents duplicates.
-- -----------------------------------------------------------------------------
CREATE TABLE applications (
    id                  BIGSERIAL       PRIMARY KEY,
    student_id          BIGINT          NOT NULL REFERENCES students (id),
    placement_drive_id  BIGINT          NOT NULL REFERENCES placement_drives (id),
    status              VARCHAR(50)     NOT NULL DEFAULT 'NOT_STARTED'
                            CHECK (status IN (
                                'NOT_STARTED', 'ELIGIBLE', 'NOT_ELIGIBLE',
                                'APPLIED', 'SHORTLISTED', 'REJECTED', 'COMPLETED'
                            )),
    applied_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_applications_student_drive UNIQUE (student_id, placement_drive_id)
);

CREATE INDEX idx_applications_student_id         ON applications (student_id);
CREATE INDEX idx_applications_placement_drive_id ON applications (placement_drive_id);

-- -----------------------------------------------------------------------------
-- notifications
-- Tracks personalised notifications dispatched to students.
-- Idempotency is enforced via unique (student_id, placement_drive_id,
-- notification_type, channel) to prevent sending the same notification twice.
-- -----------------------------------------------------------------------------
CREATE TABLE notifications (
    id                  BIGSERIAL       PRIMARY KEY,
    student_id          BIGINT          NOT NULL REFERENCES students (id),
    placement_drive_id  BIGINT          NOT NULL REFERENCES placement_drives (id),
    notification_type   VARCHAR(50)     NOT NULL
                            CHECK (notification_type IN (
                                'ELIGIBILITY', 'SHORTLIST', 'DEADLINE', 'REMINDER'
                            )),
    channel             VARCHAR(50)     NOT NULL
                            CHECK (channel IN (
                                'WHATSAPP', 'TELEGRAM', 'EMAIL', 'IN_APP'
                            )),
    status              VARCHAR(50)     NOT NULL DEFAULT 'PENDING'
                            CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'SKIPPED')),
    sent_at             TIMESTAMPTZ,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notifications_student_id         ON notifications (student_id);
CREATE INDEX idx_notifications_placement_drive_id ON notifications (placement_drive_id);
CREATE INDEX idx_notifications_status             ON notifications (status);

-- -----------------------------------------------------------------------------
-- reminder_tasks
-- Represents a scheduled deadline reminder for a student and drive.
-- UNIQUE on (student_id, placement_drive_id) prevents duplicate reminders.
-- -----------------------------------------------------------------------------
CREATE TABLE reminder_tasks (
    id                  BIGSERIAL       PRIMARY KEY,
    student_id          BIGINT          NOT NULL REFERENCES students (id),
    placement_drive_id  BIGINT          NOT NULL REFERENCES placement_drives (id),
    scheduled_for       TIMESTAMPTZ     NOT NULL,
    status              VARCHAR(50)     NOT NULL DEFAULT 'PENDING'
                            CHECK (status IN ('PENDING', 'COMPLETED', 'CANCELLED', 'FAILED')),
    completed_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_reminder_tasks_student_drive UNIQUE (student_id, placement_drive_id)
);
